name: LiveFleaPrice Fetcher

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *' # Runs every hour

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm ci
      - run: npm run fetch

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: |
            - prices.json
            - prices-regular.json
            - prices-pve.json
          message: 'Update prices'
          
      - name: Trigger Sync to Gitea workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"event_type": "sync-to-gitea"}' \
            https://api.github.com/repos/MiKueYu/SPT-LiveFleaPriceDB/dispatches