name: LiveFleaPrice Fetcher

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */5 * * *' # Runs every hour

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm ci
      - run: npm run fetch

      - name: Add Gitea remote
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan gitea.com >> ~/.ssh/known_hosts
          git remote add gitea git@gitea.com:MiKueYu/SPT-LiveFleaPriceDB.git

      - name: Pull latest changes
        run: git pull origin main

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: |
            - prices.json
            - prices-regular.json
            - prices-pve.json
          message: 'Update prices'

      - name: Push changes to Gitea
        run: git push gitea main