name: Sync to Gitee

on:
  workflow_run:
    workflows: ["LiveFleaPrice Fetcher"]
    types:
      - completed

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sync to Gitee
        uses: wei/git-sync@v3
        with:
          source_repo: ${{ github.repository }}
          source_branch: ${{ github.ref }}
          destination_repo: https://${{ secrets.GITEE_TOKEN }}@gitee.com/MiKueYu/SPT-LiveFleaPriceDB.git
          destination_branch: master  # 根据您的 Gitee 仓库主分支名称修改
          sync_direction: forward
