name: Sync specific files to Gitee

on:
  workflow_run:
    workflows: ["LiveFleaPrice Fetcher"]
    types:
      - completed

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git for Gitee
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Pull from Gitee (if exists)
        run: git clone https://${{ secrets.GITEE_TOKEN }}@gitee.com/skwn123456/spt-live-flea-price-db.git

      - name: Copy specific files
        run: |
          cp prices-pve.json prices-regular.json spt-live-flea-price-db/

      - name: Commit and push specific files to Gitee
        run: |
          cd spt-live-flea-price-db
          git add prices-pve.json prices-regular.json
          git commit -m "Sync prices-pve.json and prices-regular.json"
          git push origin main
