name: Sync To JiHuLab

on:
    workflow_run:
      workflows: ["LiveFleaPrice Fetcher"]
      types:
        - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to JiHuLab
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 JIHU_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.JIHU_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:MiKueYu/SPT-LiveFleaPriceDB.git
          # 注意替换为你的 JiHuLab 目标仓库地址
          destination-repo: git@jihulab.com:Miku_Sa/SPT-LiveFleaPriceDB.git
