name: Sync to Gitea

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sync to Gitea
        uses: wei/git-sync@v3
        with:
          source_repo: ${{ github.repository }}
          source_branch: ${{ github.ref }}
          destination_repo: https://${{ secrets.GITEA_TOKEN }}@gitea.com/MiKueYu/SPT-LiveFleaPriceDB.git
<<<<<<< HEAD
          destination_branch: main
          sync_direction: forward
=======
          destination_branch: main  #  根据您的 Gitea 仓库主分支名称修改
          sync_direction: forward
          
>>>>>>> parent of a83e23a (ok)
