name: Demo

on:
  workflow_run:
    workflows: ["LiveFleaPrice Fetcher"]
    types:
      - completed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # 使用最新稳定版本

      - name: Async Github Branch To Gitee
        uses: shanghaobo/github-branch-gitee@v1.0.0  # 使用具体的版本标签
        with:
          github_repo: MiKueYu/SPT-LiveFleaPriceDB
          github_branch: main
          gitee_repo: skwn123456/spt-live-flea-price-db
          gitee_branch: master
          username: ${{ secrets.GITEE_USERNAME }}
          password: ${{ secrets.GITEE_PASSWORD }}
