name: Demo

on:
  workflow_run:
    workflows: ["LiveFleaPrice Fetcher"]
    types:
      - completed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # 使用最新稳定版本

      - name: Commit only selected files
        run: |
          # 删除已有的 Git 配置并重新初始化
          rm -rf .git  # 删除已有的 Git 配置
          git init     # 重新初始化 Git 仓库
          git remote add origin https://gitee.com/skwn123456/spt-live-flea-price-db.git
          
          # 从 GitHub 仓库的 main 分支拉取数据
          git fetch origin main

          # 将需要提交的文件添加到索引中
          git add prices-regular.json prices-pve.json
          git commit -m "Update prices" || echo "No changes to commit"  # 如果没有更改，则跳过提交

      - name: Set up Gitee credentials
        run: |
          # 使用 Gitee 用户名和密码进行身份验证
          git config --global user.name "${{ secrets.GITEE_USERNAME }}"
          git config --global user.password "${{ secrets.GITEE_PASSWORD }}"

      - name: Push to Gitee
        run: |
          # 推送 GitHub 仓库的 main 分支内容到 Gitee 仓库的 master 分支
          git push https://$GITEE_USERNAME:${{ secrets.GITEE_PASSWORD }}@gitee.com/skwn123456/spt-live-flea-price-db.git main:master --force
        env:
          GITEE_USERNAME: ${{ secrets.GITEE_USERNAME }}
          GITEE_PASSWORD: ${{ secrets.GITEE_PASSWORD }}
