name: Sync To GitLab

on:
    workflow_run:
      workflows: ["LiveFleaPrice Fetcher"]
      types:
        - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to GitLab
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITLAB_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITLAB_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:MiKueYu/SPT-LiveFleaPriceDB.git
          # 注意替换为你的 GitLab 目标仓库地址
          destination-repo: git@gitlab.com:GuRua/spt-livefleapricedb.git
